In [1]:
import numpy as np
from tensorflow.keras.layers import Embedding, Flatten, Dense
from tensorflow.keras.models import Sequential
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.preprocessing.sequence import pad_sequences

In [2]:
docs = ['additional income',
		'best price',
        'big bucks',
        'cash bonus',
        'earn extra cash',
        'spring savings certificate',
        'valero gas marketing',
        'all domestic employees',
        'nominations for oct',
        'confirmation from spinner']

labels = np.array([1,1,1,1,1,0,0,0,0,0])

In [3]:
vocab_size = 50
encoded_docs = [one_hot(d, vocab_size) for d in docs]
print(encoded_docs)

[[47, 35], [46, 33], [20, 22], [5, 12], [8, 40, 5], [35, 6, 16], [16, 40, 44], [14, 8, 30], [17, 33, 29], [40, 16, 15]]


In [4]:
max_length = 4
padded_docs = pad_sequences(encoded_docs, maxlen=max_length, padding='post')
print(padded_docs)

[[47 35  0  0]
 [46 33  0  0]
 [20 22  0  0]
 [ 5 12  0  0]
 [ 8 40  5  0]
 [35  6 16  0]
 [16 40 44  0]
 [14  8 30  0]
 [17 33 29  0]
 [40 16 15  0]]


In [5]:
model = Sequential()
model.add(Embedding(vocab_size, 8, input_length=max_length))
model.add(Flatten())
model.add(Dense(1, activation='sigmoid'))

model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/embedding.py:100: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [6]:
model.fit(padded_docs, labels, epochs=50, verbose=0)

loss, accuracy = model.evaluate(padded_docs, labels, verbose=0)
print('정확도=',accuracy)

정확도= 1.0


In [7]:
test_doc = ['big income']
encoded_docs = [one_hot(d, vocab_size) for d in test_doc]
padded_docs = pad_sequences(encoded_docs, maxlen=max_length, padding='post')
print(model.predict(padded_docs))

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 100ms/step
[[0.5854013]]
